/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
/**
 *
 * @author lilli
 */
public class Frame4 extends javax.swing.JFrame {

    /**
     * Creates new form CompareAnswers
     */
    public Frame4() {
        initComponents();
        
        // Clear the text area first
        useranswers.setText(""); 
    
        // Path to your file
        File file = new File("message.txt"); 
        
        // This list will temporarily hold all valid judgments from the file
        ArrayList<String> judgments = new ArrayList<>();
    
    try (Scanner scanner = new Scanner(file)) {
        // 1. Read the entire file and collect all valid data
        while (scanner.hasNextLine()) {
            String line = scanner.nextLine();
            String[] parts = line.split("\\|");
            
            if (parts.length >= 2) {
                judgments.add(parts[1].trim());
            }
        }
        
        // 2. Determine where the last 8 lines start
        // If the file has fewer than 8 lines, start from 0
        int startIndex = Math.max(0, judgments.size() - 8);
        int displayNum = 1; // Always start numbering visually from 1
        
        // 3. Print only the last 8 items to your JTextArea
        for (int i = startIndex; i < judgments.size(); i++) {
            useranswers.append(displayNum + ". You selected: " + judgments.get(i) + "\n");
            displayNum++;
        }
        
    } catch (FileNotFoundException e) {
        useranswers.setText("Error: message.txt file not found.");
        e.printStackTrace();
    }
    
    //-------------------------------------------------------------------------------------------
    // Arrays to hold total "ethical" and "unethical" counts for each of the 8 questions
    // Index 0 corresponds to Question 1, Index 1 to Question 2, etc.
    int[] ethicalCounts = new int[8];
    int[] unethicalCounts = new int[8];
    
    try (Scanner scanner = new Scanner(file)) {
        int globalLineCounter = 0;
        
        // 1. Scan the entire history of the file
        while (scanner.hasNextLine()) {
            String line = scanner.nextLine();
            String[] parts = line.split("\\|");
            
            if (parts.length >= 2) {
                // Determine which question number (1-8) this line represents
                int questionIndex = globalLineCounter % 8; 
                String judgment = parts[1].trim().toLowerCase();
                
                if (judgment.equals("ethical")) {
                    ethicalCounts[questionIndex]++;
                } else if (judgment.equals("unethical")) {
                    unethicalCounts[questionIndex]++;
                }
                
                globalLineCounter++;
            }
        }
        
        // 2. Calculate percentages and display them
        for (int i = 0; i < 8; i++) {
            int totalAnswers = ethicalCounts[i] + unethicalCounts[i];
            int questionNum = i + 1;
            
            if (totalAnswers > 0) {
                // Calculate percentages safely using double casting
                double ethicalPercent = ((double) ethicalCounts[i] / totalAnswers) * 100;
                double unethicalPercent = ((double) unethicalCounts[i] / totalAnswers) * 100;
                
                // Format strings to show 1 decimal place (e.g., 75.0%)
                stats.append(String.format("%d. Ethical: %.1f%% | Unethical: %.1f%%\n", 
                        questionNum, ethicalPercent, unethicalPercent));
            } else {
                // Handling case where no data exists yet for this question position
                stats.append(questionNum + ". No data recorded yet.\n");
            }
        }
        
    } catch (FileNotFoundException e) {
        stats.setText("Error: message.txt file not found.");
        e.printStackTrace();
    }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnhome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        useranswers = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        stats = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        returnhome.setText("Back to Home Page");
        returnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnhomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 18)); // NOI18N
        jLabel1.setText("Answer % Comparisons");

        useranswers.setColumns(20);
        useranswers.setRows(5);
        jScrollPane1.setViewportView(useranswers);

        jLabel2.setText("Your Answers");

        jLabel3.setText("Global Comparison");

        stats.setColumns(20);
        stats.setRows(5);
        jScrollPane2.setViewportView(stats);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(returnhome)
                                .addGap(0, 65, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addGap(15, 15, 15)
                .addComponent(returnhome)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnhomeActionPerformed
        Frame1.counter = 0;
        this.setVisible(false);
        new Frame1().setVisible(true);
    }//GEN-LAST:event_returnhomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton returnhome;
    private javax.swing.JTextArea stats;
    private javax.swing.JTextArea useranswers;
    // End of variables declaration//GEN-END:variables
}
