/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 343479150
 */
public class Frame2 extends javax.swing.JFrame {
    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
        scenario.setText(Frame1.counter +" "+Frame1.array[Frame1.counter-1].getCaseTitle());
        catergory.setText(Frame1.array[Frame1.counter-1].getCaseCategory());
        description.setText("" + Frame1.array[Frame1.counter-1].getCaseDescription());
        Frame1.array[Frame1.counter-1].verdict.setReason(jTextField2.getText());
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        niceTabHeader = new javax.swing.JPanel();
        uselessbutton1 = new javax.swing.JRadioButton();
        uselessbutton2 = new javax.swing.JRadioButton();
        exit = new javax.swing.JButton();
        uselessbutton3 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        title1 = new javax.swing.JLabel();
        scenario = new javax.swing.JLabel();
        infoForUser = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        catergory = new javax.swing.JLabel();
        ethical = new javax.swing.JRadioButton();
        unethical = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        userReason = new javax.swing.JPanel();
        title3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uselessbutton1.setText(" ");

        uselessbutton2.setText(" ");

        exit.setBackground(new java.awt.Color(255, 153, 153));
        exit.setText("X"); // NOI18N
        exit.setToolTipText("");

        uselessbutton3.setText(" ");

        jTextPane2.setEditable(false);
        jTextPane2.setText("https://wwvv.notavirus.com/embed/ASYIfd?feature=fileloop");
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout niceTabHeaderLayout = new javax.swing.GroupLayout(niceTabHeader);
        niceTabHeader.setLayout(niceTabHeaderLayout);
        niceTabHeaderLayout.setHorizontalGroup(
            niceTabHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(niceTabHeaderLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uselessbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uselessbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uselessbutton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );
        niceTabHeaderLayout.setVerticalGroup(
            niceTabHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(niceTabHeaderLayout.createSequentialGroup()
                .addGroup(niceTabHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, niceTabHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exit)
                        .addComponent(uselessbutton1)
                        .addComponent(uselessbutton2)
                        .addComponent(uselessbutton3)))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(niceTabHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 494, -1));

        title1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 16)); // NOI18N
        title1.setText("Scenario #");
        title1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 126, 20));

        scenario.setFont(new java.awt.Font("Perpetua Titling MT", 1, 16)); // NOI18N
        scenario.setText("<num> caseTitle");
        scenario.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(scenario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 330, 20));

        title2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        title2.setText("categorY:");
        title2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        catergory.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        catergory.setText("categorY");
        catergory.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        buttonGroup1.add(ethical);
        ethical.setText("Ethical");
        ethical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ethicalActionPerformed(evt);
            }
        });

        buttonGroup1.add(unethical);
        unethical.setText("Unethical");

        description.setEditable(false);
        description.setColumns(20);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        javax.swing.GroupLayout infoForUserLayout = new javax.swing.GroupLayout(infoForUser);
        infoForUser.setLayout(infoForUserLayout);
        infoForUserLayout.setHorizontalGroup(
            infoForUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(infoForUserLayout.createSequentialGroup()
                .addGroup(infoForUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoForUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(catergory, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoForUserLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(ethical)
                        .addGap(47, 47, 47)
                        .addComponent(unethical))
                    .addGroup(infoForUserLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        infoForUserLayout.setVerticalGroup(
            infoForUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoForUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(infoForUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title2)
                    .addComponent(catergory, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoForUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ethical)
                    .addComponent(unethical))
                .addGap(138, 138, 138))
        );

        getContentPane().add(infoForUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 500, 160));

        title3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        title3.setText("Reason:");

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userReasonLayout = new javax.swing.GroupLayout(userReason);
        userReason.setLayout(userReasonLayout);
        userReasonLayout.setHorizontalGroup(
            userReasonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userReasonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 344, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userReasonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(userReasonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)))
        );
        userReasonLayout.setVerticalGroup(
            userReasonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userReasonLayout.createSequentialGroup()
                .addComponent(title3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(42, 42, 42))
        );

        getContentPane().add(userReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        scenario.setText(Frame1.counter+1 +" "+Frame1.array[Frame1.counter].getCaseTitle());
        catergory.setText(Frame1.array[Frame1.counter].getCaseCategory());
        description.setText("" + Frame1.array[Frame1.counter].getCaseDescription());
        Frame1.array[Frame1.counter].verdict.setReason(jTextField2.getText());
            

        if (ethical.isSelected()) {
            Frame1.ethicalcount++;
            buttonGroup1.clearSelection();
            Frame1.counter++;
            
        } else if (unethical.isSelected()){
            Frame1.unethicalcount++;
            buttonGroup1.clearSelection();
            Frame1.counter++;
            
        } else {
            new Frame2().setVisible(true);
            this.setVisible(false);
        }
            

        
        if (Frame1.counter == 8){
            new Frame3().setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ethicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ethicalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ethicalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel catergory;
    private javax.swing.JTextArea description;
    private javax.swing.JRadioButton ethical;
    private javax.swing.JButton exit;
    private javax.swing.JPanel infoForUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JPanel niceTabHeader;
    private javax.swing.JLabel scenario;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JRadioButton unethical;
    private javax.swing.JRadioButton uselessbutton1;
    private javax.swing.JRadioButton uselessbutton2;
    private javax.swing.JRadioButton uselessbutton3;
    private javax.swing.JPanel userReason;
    // End of variables declaration//GEN-END:variables
}
